FROM public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.4
COPY main-page.js /app/public/components/
COPY main-page.pug /app/public/components/
COPY app.bundle.js.map /app/dist/public/
COPY app.bundle.js /app/dist/public/
