apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ngc-mirror
  name: ngc-mirror-pvc
  namespace: ngc-mirror
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
  storageClassName: ddn-exa
