apiVersion: v1
data:
  ngc-update.sh: |
    #!/bin/bash
    ngc_replicator \
      --api-key=cmUxdGhqaXVqMWg5dHR2cW1hY2FkNGpjdDg6MDE1ZTAxOTktMWUzNS00ZmUxLWI5YTMtMGE5MDNkZDZmYTRj \
      --min-version=21.09 \
      --image=tensorflow --image=pytorch --image=digits --image=tensorrt \
      --registry-url=harbor.dikti.local \
      --registry-username=admin \
      --registry-password=mxqJLXtYNxBjgwk7 \
      --no-exporter \
      --strict-name-match
kind: ConfigMap
metadata:
  name: ngc-mirror-config
  namespace: ngc-mirror
